# Theme metadata
name = "NTUAIS Theme"
license = "MIT"
licenselink = "https://github.com/NTUAIS/NTUAIS.github.io/blob/main/LICENSE"
description = "A modern, dark theme for AI Safety organizations"

[author]
  name = "NTUAIS"

[original]
  name = "Custom Theme"
  homepage = "https://ntuais.github.io"
